spring:
  datasource:
    url: jdbc:mysql://localhost:3306/corenuts
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 7777